# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=25)),
            ],
        ),
    ]
